manifest_version: 1
name: ros1_noetic_params
version: "0.1.0"

kernel:
  api: ">=0.1.0,<0.2.0"

platform:
  os: [linux]

ros:
  required: true
  version: 1
  distros: [noetic]

dependencies:
  cmake: [yaml-cpp]
  ros: [roscpp, dynamic_reconfigure]

build:
  type: catkin
